import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cx } from "class-variance-authority";
import Header from "../components/Header";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./Providers";
import AuthRefresher from "./auth/AuthRefresher";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          "bg-slate-800 text-slate-200 h-[100vh] overflow-y-scroll dark"
        )}
      >
        <Providers>
          <AuthRefresher />
          <Header />
          <Suspense fallback="Loading...">{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
