version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      # These should be in .env and not commited on git, but this is simpler for a demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # backend:
  #   build: ./todo-backend
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./todo-backend:/app

  # frontend:
  #   build: ./todo-frontend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./todo-frontend:/app
