version: "3.8"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      # These should be in .env and not commited on git, but this is simpler for a demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    container_name: fastapi
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true # docker run -t

  frontend:
    container_name: next
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
