# Use the official Python base image
FROM python:3.10
# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY pyproject.toml .
# Install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="${PATH}:/root/.local/bin"
# Install the Python dependencies
RUN poetry install
COPY . .
ENV PRISMA_BINARY_CACHE_DIR=/prisma/binaries
RUN poetry run prisma py fetch
RUN poetry run prisma generate
ENV DB_ADDRESS=db:5432
# ENV PRISMA_BINARY_CACHE_DIR=/prisma/binaries/node_modules/prisma/
# Run a script for prisma 
# COPY ./initprisma.sh .
# RUN ./initprisma.sh
# Expose the port that the app will run on
EXPOSE 8000
# Start the FastAPI app
CMD poetry run uvicorn app:app --host 0.0.0.0 --port 8000 --reload
# CMD bash
